CREATE DATABASE IF NOT EXISTS hms;
USE hms;

CREATE TABLE Hospital (
HospitalID INT PRIMARY KEY AUTO_INCREMENT,
H_name VARCHAR(50) DEFAULT 'Not Entered'
);

CREATE TABLE Locations (
LocationID INT PRIMARY KEY AUTO_INCREMENT,
City VARCHAR(50) DEFAULT 'Not Entered',
Country VARCHAR(50) DEFAULT 'Not Entered'
);

CREATE TABLE Branches (
BranchID INT PRIMARY KEY AUTO_INCREMENT,
HospitalID INT NOT NULL,
LocationID INT NOT NULL,
CONSTRAINT fk_brnch_hos FOREIGN KEY (HospitalID) REFERENCES Hospital(HospitalID) ON DELETE CASCADE,
CONSTRAINT fk_brnch_loc FOREIGN KEY (LocationID) REFERENCES Locations(LocationID) ON UPDATE CASCADE
);

CREATE TABLE Departments (
DeptID INT PRIMARY KEY AUTO_INCREMENT,
Dept_name VARCHAR(50) DEFAULT 'Not Entered',
HospitalID INT,
CONSTRAINT FOREIGN KEY (HospitalID) REFERENCES Hospital(HospitalID) ON DELETE SET NULL
);

CREATE TABLE Laboratories (
LabID INT NOT NULL AUTO_INCREMENT,
DeptID INT NOT NULL,
PRIMARY KEY(LabID,DeptID),
CONSTRAINT fk_lab_dept FOREIGN KEY (DeptID) REFERENCES Departments(DeptID)
);

CREATE TABLE Users (
UserID INT PRIMARY KEY AUTO_INCREMENT,
User_name VARCHAR(50) NOT NULL,
Birthyear DATE NOT NULL,
Gender ENUM('Male','Female') NOT NULL,
Email VARCHAR(50) NOT NULL,
Pass VARCHAR(255) NOT NULL,
img VARCHAR(255) DEFAULT "/images/profile-img.webp",
Role ENUM('Patient', 'Doctor', 'Admin') DEFAULT 'Patient'
);

CREATE TABLE Doctors (
DoctorID INT PRIMARY KEY,
BranchID INT, 
img varchar(255) DEFAULT "/images/profile-img.webp",
Fee INT Default "1000",
Experiances VARCHAR(100) Default "Something Went Wrong",
CONSTRAINT fk_doc_brnch FOREIGN KEY (BranchID) REFERENCES Branches(BranchID) ON DELETE SET NULL,
CONSTRAINT fk_doc_users FOREIGN KEY (DoctorID) REFERENCES Users(UserID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Schedules (
DoctorID INT NOT NULL,
ScDays VARCHAR(15),
Slots INT DEFAULT ('5'),
PRIMARY KEY (DoctorID,ScDays),
CONSTRAINT fk_sc_doc FOREIGN KEY (DoctorID) REFERENCES Doctors(DoctorID) ON DELETE CASCADE
);

CREATE TABLE Specialties (
SpID INT PRIMARY KEY AUTO_INCREMENT,
S_name VARCHAR(50) DEFAULT 'Not Entered'
);

CREATE TABLE Doctor_Specialty (
DoctorID INT NOT NULL,
SpID INT NOT NULL,
PRIMARY KEY(DoctorID,SpID),
CONSTRAINT fk_dsp_doc FOREIGN KEY (DoctorID) REFERENCES Doctors(DoctorID) ON DELETE CASCADE,
CONSTRAINT fk_dsp_sp FOREIGN KEY (SpID) REFERENCES Specialties(SpID)
);

CREATE TABLE Patients (
PatientID INT PRIMARY KEY,
img varchar(255) DEFAULT "/images/profile-img.webp",
CONSTRAINT fk_pat_users FOREIGN KEY (PatientID) REFERENCES Users(UserID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Appointments (
AppointID INT PRIMARY KEY AUTO_INCREMENT,
A_date Date NOT NULL,
A_time TIME DEFAULT '17:00:00',
Status VARCHAR(30) DEFAULT 'Pending',
PatientID INT NOT NULL,
DoctorID INT NOT NULL,
SerialNo INT NOT NULL,
CONSTRAINT fk_app_doc FOREIGN KEY (DoctorID) REFERENCES Doctors(DoctorID) ON DELETE CASCADE,
CONSTRAINT fk_app_pat FOREIGN KEY (PatientID) REFERENCES Patients(PatientID) ON DELETE CASCADE
);

CREATE TABLE Diagnoses (
TestID INT PRIMARY KEY AUTO_INCREMENT,
Test_name VARCHAR(50) NOT NULL,
Test_price INT NOT NULL,
LabID INT NOT NULL,
CONSTRAINT fk_diag_lab FOREIGN KEY (LabID) REFERENCES Laboratories(LabID)
);

CREATE TABLE DiagnosesHistory(
DiagnosisID INT PRIMARY KEY AUTO_INCREMENT,
Diagnosis_Date DATETIME NOT NULL,
TestID INT NOT NULL,
PatientID INT NOT NULL,
CONSTRAINT fk_diagh_pat FOREIGN KEY (PatientID) REFERENCES Patients(PatientID) ON DELETE CASCADE,
CONSTRAINT fk_diagh_lab FOREIGN KEY (TestID) REFERENCES Diagnoses(TestID) ON UPDATE CASCADE
);